### ISSUE TITLE
Add credentials input

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/preview-action#16]
At this moment the preview action supports connecting DockerHub and GHCR credentials. It must support credentials for other types of registries too (Google, Amazon, Azure, custom docker registries).

**Comment by moklidia** [comment]
Create a pull request like this from the same branch:
https://github.com/UffizziCloud/example-voting-app/pull/66/files

Confirm that AWS, Google cloud, and custom docker hub registry credentials have been created.
Need to obtain valid Azure credentials and add them to repository secrets to be able to test Azure connection.

**Comment by NealArw** [comment]
**TESTED - OK**
