### ISSUE TITLE
Delete GHCR images after closing PR

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/preview-action#19]
Some potential users have requested that the images be deleted from GHCR once the preview is destroyed to save storage cost on GitHub.

**Comment by gadkins** [comment]
Delete images:
- On push to open PR
- When PR is closed

**Comment by axisofentropy** [comment]
We're now advocating ephemeral container registries like https://ttl.sh

**Comment by waveywaves** [comment]
Closing this issue as we are using ephemeral container registry registry.uffizzi.com instead.
