### ISSUE TITLE
Pass creation source to CLI

### ISSUE THREAD

**Issue by greenfrontend** [UffizziCloud/preview-action#54]
We need to pass creation_source = github_actions to CLI
Related platform issue https://github.com/UffizziCloud/uffizzi_platform/issues/671

**Comment by NealArw** [comment]
**TESTED on prod - OK**

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/89470900/212667459-0084ba43-0da1-4c21-9707-1516e6371bb8.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/212667521-6f6ebbbb-b416-4d5e-8adf-c250f6004e5c.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/212667583-4b970081-2f28-4114-8e9f-34561c39a6d4.png">
