### ISSUE TITLE
Add link to deployment details in GHA comment

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/preview-action#7]
When the reusable workflow is called, it posts the preview URL (https://github.com/UffizziCloud/preview-action/blob/67edbbf0427bf204e7718f279f7d7ed22c725cba/.github/workflows/reusable.yaml#L146-L149). 

We should also post a link to the deployment details in the Uffizzi UI. For example:

> View deployment details: https://app.uffizzi.com/projects/16/deployments/4724/containers

**Comment by gadkins** [comment]
**Developer should test**:  

Test this issue using GitHub Actions ([see example here](https://github.com/UffizziCloud/example-voting-app/blob/main/.github/workflows/uffizzi-previews.yml)).

Verify the following:  
- [ ] The Uffizzi preview URL is posted and works  
- [ ] The Uffizzi preview ID is posted  
- [ ] A link to the deployment details is posted and takes the user to the correct deployment in the Uffizzi Dashboard

**Comment by zipofar** [comment]
https://github.com/UffizziCloud/uffizzi_cli/issues/144

**Comment by antlu** [comment]
Verified
> **github-actions** bot commented 9 minutes ago
>
> Uffizzi Preview deployed at URL:
> https://deployment-2258-project1-h5cx.app.qa-gke.uffizzi.com
> 
> Uffizzi Preview deployment details at URI:
> https://app.qa-gke.uffizzi.com/projects/311/deployments/2258/containers
> 
> Uffizzi Preview ID: deployment-2258
