### ISSUE TITLE
Automatically create project from repo name

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/preview-action#8]
Currently in our GHA reusable workflow we have the parameter [`project`](https://github.com/UffizziCloud/example-voting-app/blob/8f78f9204c8869aca538cb929d49c5b1074da8ff/.github/workflows/uffizzi-previews.yml#L176) which takes as input the Uffizzi project slug. We should change our GHA to use the repo name as the value of `project`. This reduces the number of inputs required by the end user when setting up the Uffizzi GHA.

**Comment by gadkins** [comment]
We should be sure that if the project doesn't exist that matches the name of the repo, then we should create a new one.

**Comment by gadkins** [comment]
We should also probably consider adding the option to create a project on the fly with the `uffizzi preview create` command. For example, something like `uffizzi preview create docker-compose.uffizzi.yml -p my-new-project`, where `-p` tells Uffizzi this preview should be created in a new project called `-p`.

**Comment by gadkins** [comment]
**Developer should test**:  

Test this issue using GitHub Actions ([see example here](https://github.com/UffizziCloud/example-voting-app/blob/main/.github/workflows/uffizzi-previews.yml)).

- [ ]  Verify that the GitHub Action reusable workflow does **not** require a `project` input  
- [ ] Verify that a new project is created in Uffizzi when using the GitHub Actions [reusable workflow](https://github.com/UffizziCloud/preview-action/blob/master/.github/workflows/reusable.yaml) from a new repo  
- [ ] Verify that a new project is **not** created in Uffizzi when using the GitHub Actions [reusable workflow](https://github.com/UffizziCloud/preview-action/blob/master/.github/workflows/reusable.yaml) form a repo that already has a Uffizzi project configured for it   
- [ ] Verify that you can update the preview for the given project  
- [ ] Delete the project from Uffizzi, and verify that when the GitHub Actions [reusable workflow](https://github.com/UffizziCloud/preview-action/blob/master/.github/workflows/reusable.yaml) runs, it creates a new project in Uffizzi again

**Comment by moklidia** [comment]
@gadkins Should the project name be the full repo name? `UffizziCloud/uffizzi_app` or just `uffizzi_app`?

**Comment by moklidia** [comment]
If the user does not provide the username/password inputs but provides a project name - create a project with that name for him.

**Comment by gadkins** [comment]
Implemented. Moving https://github.com/UffizziCloud/preview-action/issues/8#issuecomment-1220960593 to its own issue here https://github.com/UffizziCloud/uffizzi_platform/issues/440
